# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# development:
#   facebook_app_id: <%= ENV["1172202416177756"] %>
#   facebook_secret: <%= ENV["98622da3f65d33d7eaf75f793947a92b"] %>
#   domain_name: localhost:3000
#   secret_key_base: f8a8167e2cbeec9534e29248e84fb5a8ec5a7ff4bc798cd8f030cfdcebb63ffa5eece15eb2d26a163fc1ce504b5a3bd9cfba8de08b2425647bfc7fc5c8c168ba

# test:
#   secret_key_base: 690b086066c2d803d9a3985675a200073696c7fc9ddae542dbc7e8b81f9fe81c212013e1b98990178deb9b3ad7e991a615fe128571e61e8ccebcac603c76f68c

# # Do not keep production secrets in the repository,
# # instead read values from the environment.
# production:
#   facebook_app_id: <%= ENV["1172202416177756"] %>
#   facebook_secret: <%= ENV["98622da3f65d33d7eaf75f793947a92b"] %>
#   domain_name: <%= ENV["localhost:3000"] %>
#   secret_key_base: <%= ENV["f8a8167e2cbeec9534e29248e84fb5a8ec5a7ff4bc798cd8f030cfdcebb63ffa5eece15eb2d26a163fc1ce504b5a3bd9cfba8de08b2425647bfc7fc5c8c168ba"] %>

development:
  secret_key_base: e59cb3145c1fc1e7ca4ea1c7f5631996017892e80b521368606c9fac3a94367c741261fde7c8054ba2e891b07012833a93ebc02fa7a47a32bd1b7938e41fd34c

test:
  secret_key_base: 15ee9e73917af58cb3f52f69b5aaf598768db2770da021bc8baea0b7f104342d2da592f0b9d29c81ec97f93e1c9c725f65d2861b5fe3171ca6736f8a1ae9ab98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>